/* Automatically generated by wasm2c */
#ifndef WATCH_H_GENERATED_
#define WATCH_H_GENERATED_

#include <stdint.h>

#include "wasm-rt.h"

#if defined(WASM_RT_ENABLE_SIMD)
#include "simde/wasm/simd128.h"
#endif

/* TODO(binji): only use stdint.h types in header */
#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

#if defined(WASM_RT_ENABLE_SIMD)
typedef simde_v128_t v128;
#endif

#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
struct w2c_wasi__snapshot__preview1;

typedef struct w2c_watch {
  struct w2c_env* w2c_env_instance;
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  u32 w2c_g3;
  u32 w2c_0x5F_start_em_asm;
  u32 w2c_0x5F_stop_em_asm;
  u32 w2c_g6;
  u32 w2c_g7;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_indirect_function_table;
} w2c_watch;

void wasm2c_watch_instantiate(w2c_watch*, struct w2c_env*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_watch_free(w2c_watch*);
wasm_rt_func_type_t wasm2c_watch_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' '__assert_fail' */
void w2c_env_0x5F_assert_fail(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'emscripten_asm_const_double' */
f64 w2c_env_emscripten_asm_const_double(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'emscripten_asm_const_int' */
u32 w2c_env_emscripten_asm_const_int(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'emscripten_clear_interval' */
void w2c_env_emscripten_clear_interval(struct w2c_env*, u32);

/* import: 'env' 'emscripten_clear_timeout' */
void w2c_env_emscripten_clear_timeout(struct w2c_env*, u32);

/* import: 'env' 'emscripten_memcpy_big' */
void w2c_env_emscripten_memcpy_big(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'emscripten_request_animation_frame' */
u32 w2c_env_emscripten_request_animation_frame(struct w2c_env*, u32, u32);

/* import: 'env' 'emscripten_resize_heap' */
u32 w2c_env_emscripten_resize_heap(struct w2c_env*, u32);

/* import: 'env' 'emscripten_set_blur_callback_on_thread' */
u32 w2c_env_emscripten_set_blur_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_focus_callback_on_thread' */
u32 w2c_env_emscripten_set_focus_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_interval' */
u32 w2c_env_emscripten_set_interval(struct w2c_env*, u32, f64, u32);

/* import: 'env' 'emscripten_set_keydown_callback_on_thread' */
u32 w2c_env_emscripten_set_keydown_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_keyup_callback_on_thread' */
u32 w2c_env_emscripten_set_keyup_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_mousedown_callback_on_thread' */
u32 w2c_env_emscripten_set_mousedown_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_mouseout_callback_on_thread' */
u32 w2c_env_emscripten_set_mouseout_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_mouseup_callback_on_thread' */
u32 w2c_env_emscripten_set_mouseup_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_timeout' */
u32 w2c_env_emscripten_set_timeout(struct w2c_env*, u32, f64, u32);

/* import: 'env' 'emscripten_set_touchend_callback_on_thread' */
u32 w2c_env_emscripten_set_touchend_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_set_touchstart_callback_on_thread' */
u32 w2c_env_emscripten_set_touchstart_callback_on_thread(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'emscripten_sleep' */
void w2c_env_emscripten_sleep(struct w2c_env*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 w2c_wasi__snapshot__preview1_fd_write(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_watch_memory(w2c_watch* instance);

/* export: '__wasm_call_ctors' */
void w2c_watch_0x5F_wasm_call_ctors(w2c_watch*);

/* export: 'main' */
u32 w2c_watch_main(w2c_watch*, u32, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* w2c_watch_0x5F_indirect_function_table(w2c_watch* instance);

/* export: 'malloc' */
u32 w2c_watch_malloc(w2c_watch*, u32);

/* export: 'free' */
void w2c_watch_free(w2c_watch*, u32);

/* export: '__errno_location' */
u32 w2c_watch_0x5F_errno_location(w2c_watch*);

/* export: 'fflush' */
u32 w2c_watch_fflush(w2c_watch*, u32);

/* export: 'emscripten_stack_init' */
void w2c_watch_emscripten_stack_init(w2c_watch*);

/* export: 'emscripten_stack_set_limits' */
void w2c_watch_emscripten_stack_set_limits(w2c_watch*, u32, u32);

/* export: 'emscripten_stack_get_free' */
u32 w2c_watch_emscripten_stack_get_free(w2c_watch*);

/* export: 'emscripten_stack_get_base' */
u32 w2c_watch_emscripten_stack_get_base(w2c_watch*);

/* export: 'emscripten_stack_get_end' */
u32 w2c_watch_emscripten_stack_get_end(w2c_watch*);

/* export: 'stackSave' */
u32 w2c_watch_stackSave(w2c_watch*);

/* export: 'stackRestore' */
void w2c_watch_stackRestore(w2c_watch*, u32);

/* export: 'stackAlloc' */
u32 w2c_watch_stackAlloc(w2c_watch*, u32);

/* export: 'emscripten_stack_get_current' */
u32 w2c_watch_emscripten_stack_get_current(w2c_watch*);

/* export: '__start_em_asm' */
u32* w2c_watch_0x5F_start_em_asm(w2c_watch* instance);

/* export: '__stop_em_asm' */
u32* w2c_watch_0x5F_stop_em_asm(w2c_watch* instance);

/* export: 'dynCall_idi' */
u32 w2c_watch_dynCall_idi(w2c_watch*, u32, f64, u32);

/* export: 'dynCall_vi' */
void w2c_watch_dynCall_vi(w2c_watch*, u32, u32);

/* export: 'dynCall_iiii' */
u32 w2c_watch_dynCall_iiii(w2c_watch*, u32, u32, u32, u32);

/* export: 'dynCall_iii' */
u32 w2c_watch_dynCall_iii(w2c_watch*, u32, u32, u32);

/* export: 'dynCall_v' */
void w2c_watch_dynCall_v(w2c_watch*, u32);

/* export: 'dynCall_viii' */
void w2c_watch_dynCall_viii(w2c_watch*, u32, u32, u32, u32);

/* export: 'dynCall_vii' */
void w2c_watch_dynCall_vii(w2c_watch*, u32, u32, u32);

/* export: 'dynCall_iiiiii' */
u32 w2c_watch_dynCall_iiiiii(w2c_watch*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_ii' */
u32 w2c_watch_dynCall_ii(w2c_watch*, u32, u32);

/* export: 'dynCall_jiji' */
u32 w2c_watch_dynCall_jiji(w2c_watch*, u32, u32, u32, u32, u32);

/* export: 'dynCall_iidiiii' */
u32 w2c_watch_dynCall_iidiiii(w2c_watch*, u32, u32, f64, u32, u32, u32, u32);

/* export: 'asyncify_start_unwind' */
void w2c_watch_asyncify_start_unwind(w2c_watch*, u32);

/* export: 'asyncify_stop_unwind' */
void w2c_watch_asyncify_stop_unwind(w2c_watch*);

/* export: 'asyncify_start_rewind' */
void w2c_watch_asyncify_start_rewind(w2c_watch*, u32);

/* export: 'asyncify_stop_rewind' */
void w2c_watch_asyncify_stop_rewind(w2c_watch*);

/* export: 'asyncify_get_state' */
u32 w2c_watch_asyncify_get_state(w2c_watch*);

// test
static void w2c_watch_0x5F_wasm_call_ctors_0(w2c_watch*);
static void w2c_watch_f22(w2c_watch*);
static u32 w2c_watch_f23(w2c_watch*, f64, u32);
static u32 w2c_watch_f24(w2c_watch*);
static void w2c_watch_f25(w2c_watch*);
static void w2c_watch_f26(w2c_watch*, u32);
static void w2c_watch_f27(w2c_watch*, u32);
static u32 w2c_watch_f28(w2c_watch*);
static u32 w2c_watch_main_0(w2c_watch*, u32, u32);
static void w2c_watch_f30(w2c_watch*);
static void w2c_watch_f31(w2c_watch*, u32);
static void w2c_watch_f32(w2c_watch*, u32, u32);
static void w2c_watch_f33(w2c_watch*, u32);
static void w2c_watch_f34(w2c_watch*, u32);
static void w2c_watch_f35(w2c_watch*, u32);
static void w2c_watch_f36(w2c_watch*, u32, u32, u32);
static void w2c_watch_f37(w2c_watch*);
static void w2c_watch_f38(w2c_watch*, u32);
static void w2c_watch_f39(w2c_watch*, u32);
static void w2c_watch_f40(w2c_watch*, u32, u32);
static void w2c_watch_f41(w2c_watch*);
static void w2c_watch_f42(w2c_watch*);
static void w2c_watch_f43(w2c_watch*, u32, u32);
static void w2c_watch_f44(w2c_watch*, u32, u32);
static void w2c_watch_f45(w2c_watch*, u32);
static void w2c_watch_f46(w2c_watch*, u32);
static u32 w2c_watch_f47(w2c_watch*);
static void w2c_watch_f48(w2c_watch*);
static void w2c_watch_f49(w2c_watch*);
static void w2c_watch_f50(w2c_watch*);
static u32 w2c_watch_f51(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f52(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f53(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f54(w2c_watch*, u32, u32, u32);
static void w2c_watch_f55(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f56(w2c_watch*, u32, u32);
static void w2c_watch_f57(w2c_watch*);
static void w2c_watch_f58(w2c_watch*, u32, u32);
static void w2c_watch_f59(w2c_watch*);
static void w2c_watch_f60(w2c_watch*);
static void w2c_watch_f61(w2c_watch*);
static void w2c_watch_f62(w2c_watch*, u32);
static void w2c_watch_f63(w2c_watch*);
static void w2c_watch_f64(w2c_watch*);
static void w2c_watch_f65(w2c_watch*, u32, u32);
static void w2c_watch_f66(w2c_watch*);
static u32 w2c_watch_f67(w2c_watch*);
static void w2c_watch_f68(w2c_watch*);
static u32 w2c_watch_f69(w2c_watch*, u32);
static void w2c_watch_f70(w2c_watch*, u32, u32);
static u32 w2c_watch_f71(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f72(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f73(w2c_watch*, u32);
static u32 w2c_watch_f74(w2c_watch*);
static void w2c_watch_f75(w2c_watch*, u32, u32, u32);
static void w2c_watch_f76(w2c_watch*, u32);
static void w2c_watch_f77(w2c_watch*, u32, u32);
static void w2c_watch_f78(w2c_watch*);
static void w2c_watch_f79(w2c_watch*);
static u32 w2c_watch_f80(w2c_watch*);
static u32 w2c_watch_f81(w2c_watch*);
static void w2c_watch_f82(w2c_watch*, u32, u32);
static void w2c_watch_f83(w2c_watch*, u32, u32);
static void w2c_watch_f84(w2c_watch*, u32, u32);
static void w2c_watch_f85(w2c_watch*);
static void w2c_watch_f86(w2c_watch*, u32);
static void w2c_watch_f87(w2c_watch*, u32);
static u32 w2c_watch_f88(w2c_watch*, u32);
static u32 w2c_watch_f89(w2c_watch*, u32, u32, u32);
static void w2c_watch_f90(w2c_watch*, u32);
static void w2c_watch_f91(w2c_watch*, u32);
static void w2c_watch_f92(w2c_watch*, u32, u32);
static void w2c_watch_f93(w2c_watch*, u32, u32);
static void w2c_watch_f94(w2c_watch*, u32, u32);
static void w2c_watch_f95(w2c_watch*, u32, u32, u32);
static void w2c_watch_f96(w2c_watch*, u32, u32);
static void w2c_watch_f97(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f98(w2c_watch*, u32, u32);
static u32 w2c_watch_f99(w2c_watch*, u32, u32);
static u32 w2c_watch_f100(w2c_watch*, u32, u32);
static u32 w2c_watch_f101(w2c_watch*, u32, u32);
static void w2c_watch_f102(w2c_watch*, u32);
static u32 w2c_watch_f103(w2c_watch*, u32, u32);
static void w2c_watch_f104(w2c_watch*, u32);
static u32 w2c_watch_f105(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f106(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f107(w2c_watch*, u32);
static u32 w2c_watch_f108(w2c_watch*, u32, u32);
static u32 w2c_watch_f109(w2c_watch*, u32, u32);
static u32 w2c_watch_f110(w2c_watch*, u32);
static u32 w2c_watch_f111(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f112(w2c_watch*, u32, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f113(w2c_watch*, u32);
static u32 w2c_watch_f114(w2c_watch*, u32, u32, u32, u32, u32);
static void w2c_watch_f115(w2c_watch*, u32);
static u32 w2c_watch_f116(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f117(w2c_watch*, u32);
static u32 w2c_watch_f118(w2c_watch*, u32);
static void w2c_watch_f119(w2c_watch*, u32);
static u32 w2c_watch_f120(w2c_watch*, u32);
static u32 w2c_watch_f121(w2c_watch*, u32, u32);
static u32 w2c_watch_f122(w2c_watch*, u32, u32);
static u32 w2c_watch_f123(w2c_watch*, u32);
static u32 w2c_watch_f124(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f125(w2c_watch*, u32);
static u32 w2c_watch_f126(w2c_watch*, u32);
static void w2c_watch_f127(w2c_watch*, u32);
static u32 w2c_watch_f128(w2c_watch*, u32, u32);
static u32 w2c_watch_f129(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f130(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f131(w2c_watch*, u32, u32);
static void w2c_watch_f132(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f133(w2c_watch*, u32);
static u32 w2c_watch_f134(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f135(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f136(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f137(w2c_watch*, u32);
static u32 w2c_watch_f138(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f139(w2c_watch*, u32, u32);
static u32 w2c_watch_f140(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f141(w2c_watch*, u32, u32, u32, u32, u32);
static void w2c_watch_f142(w2c_watch*, u32, u32);
static void w2c_watch_f143(w2c_watch*, u32);
static u32 w2c_watch_f144(w2c_watch*, u32);
static void w2c_watch_f145(w2c_watch*, u32, u32);
static u32 w2c_watch_f146(w2c_watch*, u32, u32);
static u32 w2c_watch_f147(w2c_watch*, u32, u32);
static u32 w2c_watch_f148(w2c_watch*, u32, u32);
static void w2c_watch_f149(w2c_watch*, u32, u32);
static void w2c_watch_f150(w2c_watch*, u32);
static u32 w2c_watch_f151(w2c_watch*, u32, u32);
static void w2c_watch_f152(w2c_watch*, u32);
static u32 w2c_watch_f153(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f154(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f155(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f156(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f157(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f158(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f159(w2c_watch*, u32, u32);
static u32 w2c_watch_f160(w2c_watch*, u32, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f161(w2c_watch*, u32, u32);
static void w2c_watch_f162(w2c_watch*, u32);
static u32 w2c_watch_f163(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f164(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f165(w2c_watch*, u32, u32);
static u32 w2c_watch_f166(w2c_watch*, u32, u32);
static u32 w2c_watch_f167(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f168(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f169(w2c_watch*, u32);
static u32 w2c_watch_f170(w2c_watch*, u32, u32);
static u32 w2c_watch_f171(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f172(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f173(w2c_watch*, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f174(w2c_watch*, u32);
static u32 w2c_watch_f175(w2c_watch*, u32, u32);
static u32 w2c_watch_f176(w2c_watch*, u32, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f177(w2c_watch*, u32);
static u32 w2c_watch_f178(w2c_watch*, u32, u32);
static u32 w2c_watch_f179(w2c_watch*, u32);
static u32 w2c_watch_f180(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f181(w2c_watch*, u32, u32);
static u32 w2c_watch_f182(w2c_watch*, u32, u32);
static u32 w2c_watch_f183(w2c_watch*, u32, u32);
static u32 w2c_watch_f184(w2c_watch*, u32, u32);
static u32 w2c_watch_f185(w2c_watch*, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f186(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f187(w2c_watch*, u32, u32);
static u32 w2c_watch_f188(w2c_watch*, u32);
static u32 w2c_watch_f189(w2c_watch*, u32, u32);
static u32 w2c_watch_f190(w2c_watch*, u32);
static u32 w2c_watch_f191(w2c_watch*, u32, u32);
static void w2c_watch_f192(w2c_watch*, u32, u32);
static u32 w2c_watch_f193(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f194(w2c_watch*, u32);
static u32 w2c_watch_f195(w2c_watch*, u32);
static u32 w2c_watch_f196(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f197(w2c_watch*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);
static void w2c_watch_f198(w2c_watch*, u32, u32);
static void w2c_watch_f199(w2c_watch*, u32);
static u32 w2c_watch_f200(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f201(w2c_watch*, u32, u32);
static u32 w2c_watch_f202(w2c_watch*, u32, u32, u32, u32, u32, u32, u32);
static void w2c_watch_f203(w2c_watch*, u32);
static u32 w2c_watch_f204(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f205(w2c_watch*, u32, u32);
static u32 w2c_watch_f206(w2c_watch*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f207(w2c_watch*, u32, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f208(w2c_watch*, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f209(w2c_watch*, u32);
static u32 w2c_watch_f210(w2c_watch*, u32);
static u32 w2c_watch_f211(w2c_watch*, u32);
static u32 w2c_watch_f212(w2c_watch*, u32, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f213(w2c_watch*, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f214(w2c_watch*, u32);
static u32 w2c_watch_f215(w2c_watch*, u32);
static u32 w2c_watch_f216(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f217(w2c_watch*, u32);
static u32 w2c_watch_f218(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f219(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f220(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f221(w2c_watch*, u32, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_f222(w2c_watch*, u32, u32);
static u32 w2c_watch_f223(w2c_watch*, u32, u32, u32, u32, u32, u32, u32);
static void w2c_watch_f224(w2c_watch*, u32);
static u32 w2c_watch_f225(w2c_watch*, u32, u32);
static u32 w2c_watch_f226(w2c_watch*, u32);
static u32 w2c_watch_f227(w2c_watch*, u32, u32, u32);
static void w2c_watch_f228(w2c_watch*, u32);
static void w2c_watch_f229(w2c_watch*);
static void w2c_watch_f230(w2c_watch*);
static void w2c_watch_f231(w2c_watch*);
static void w2c_watch_f232(w2c_watch*);
static u32 w2c_watch_f233(w2c_watch*, u32, u32);
static void w2c_watch_f234(w2c_watch*);
static void w2c_watch_f235(w2c_watch*, u32);
static void w2c_watch_f236(w2c_watch*);
static void w2c_watch_f237(w2c_watch*);
static void w2c_watch_f238(w2c_watch*);
static void w2c_watch_f239(w2c_watch*);
static void w2c_watch_f240(w2c_watch*);
static void w2c_watch_f241(w2c_watch*);
static void w2c_watch_f242(w2c_watch*);
static void w2c_watch_f243(w2c_watch*);
static u32 w2c_watch_f244(w2c_watch*, u32, u32, u32);
static void w2c_watch_f245(w2c_watch*);
static void w2c_watch_f246(w2c_watch*);
static u32 w2c_watch_f247(w2c_watch*);
static void w2c_watch_f248(w2c_watch*);
static void w2c_watch_f249(w2c_watch*);
static void w2c_watch_f250(w2c_watch*);
static void w2c_watch_f251(w2c_watch*);
static void w2c_watch_f252(w2c_watch*);
static u32 w2c_watch_f253(w2c_watch*, u32, u32, u32, u32, u32);
static u32 w2c_watch_f254(w2c_watch*, u32, u32, u32, u32, u32);
static u32 w2c_watch_f255(w2c_watch*, u32, u32);
static u32 w2c_watch_f256(w2c_watch*, u32);
static u32 w2c_watch_f257(w2c_watch*);
static u32 w2c_watch_f258(w2c_watch*, u32, u32);
static u32 w2c_watch_f259(w2c_watch*);
static u32 w2c_watch_f260(w2c_watch*, u32);
static u32 w2c_watch_f261(w2c_watch*, u32);
static u32 w2c_watch_f262(w2c_watch*, u32);
static u32 w2c_watch_f263(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f264(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f265(w2c_watch*, u32, u32, u32);
static void w2c_watch_f266(w2c_watch*, u32);
static u32 w2c_watch_f267(w2c_watch*, u32, u32);
static void w2c_watch_f268(w2c_watch*, u32);
static void w2c_watch_f269(w2c_watch*, u32, u32, u32);
static void w2c_watch_f270(w2c_watch*, u32, u32);
static void w2c_watch_f271(w2c_watch*, u32, u32);
static u32 w2c_watch_f272(w2c_watch*, u32, u32, u32);
static void w2c_watch_f273(w2c_watch*, u32, u32);
static u32 w2c_watch_f274(w2c_watch*, u32, u32);
static void w2c_watch_f275(w2c_watch*, u32, u32, u32);
static void w2c_watch_f276(w2c_watch*, u32, u32);
static u32 w2c_watch_f277(w2c_watch*, u32, u32, u32);
static void w2c_watch_f278(w2c_watch*, u32);
static void w2c_watch_f279(w2c_watch*, u32, u32);
static u32 w2c_watch_f280(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f281(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_0x5F_errno_location_0(w2c_watch*);
static u32 w2c_watch_f283(w2c_watch*, u32);
static void w2c_watch_f284(w2c_watch*, u32);
static void w2c_watch_f285(w2c_watch*, u32);
static u32 w2c_watch_f286(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f287(w2c_watch*, u32, u32);
static u32 w2c_watch_f288(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f289(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f290(w2c_watch*, u32);
static u64 w2c_watch_f291(w2c_watch*, u32, u64, u32);
static u32 w2c_watch_f292(w2c_watch*, u32, u32);
static u32 w2c_watch_f293(w2c_watch*, u32, u32);
static u32 w2c_watch_f294(w2c_watch*, u32, u32);
static u32 w2c_watch_f295(w2c_watch*, u32, u32);
static u32 w2c_watch_f296(w2c_watch*, u32, u32);
static u32 w2c_watch_f297(w2c_watch*, u32, u32);
static u32 w2c_watch_f298(w2c_watch*, u32);
static u32 w2c_watch_f299(w2c_watch*, u32, u32);
static u32 w2c_watch_f300(w2c_watch*);
static void w2c_watch_f301(w2c_watch*);
static u32 w2c_watch_f302(w2c_watch*, u32);
static void w2c_watch_f303(w2c_watch*, u32);
static u32 w2c_watch_f304(w2c_watch*, u32, u32);
static u32 w2c_watch_f305(w2c_watch*, u32);
static u32 w2c_watch_f306(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f307(w2c_watch*, u32, u32);
static f64 w2c_watch_f308(w2c_watch*, f64, u32);
static u32 w2c_watch_f309(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f310(w2c_watch*, u32, u32, u32, u32, u32);
static u32 w2c_watch_f311(w2c_watch*, u32, u32, u32, u32, u32, u32, u32);
static void w2c_watch_f312(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f313(w2c_watch*, u32);
static void w2c_watch_f314(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f315(w2c_watch*, u64, u32, u32);
static u32 w2c_watch_f316(w2c_watch*, u64, u32);
static u32 w2c_watch_f317(w2c_watch*, u64, u32);
static void w2c_watch_f318(w2c_watch*, u32, u32, u32, u32, u32);
static u32 w2c_watch_f319(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f320(w2c_watch*, u32, f64, u32, u32, u32, u32);
static void w2c_watch_f321(w2c_watch*, u32, u32);
static u64 w2c_watch_f322(w2c_watch*, f64);
static u32 w2c_watch_f323(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_f324(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f325(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f326(w2c_watch*, u32);
static u32 w2c_watch_f327(w2c_watch*);
static u32 w2c_watch_f328(w2c_watch*);
static u32 w2c_watch_f329(w2c_watch*);
static void w2c_watch_f330(w2c_watch*);
static u32 w2c_watch_f331(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_f332(w2c_watch*, u32, u32);
static u32 w2c_watch_malloc_0(w2c_watch*, u32);
static void w2c_watch_free_0(w2c_watch*, u32);
static u32 w2c_watch_f335(w2c_watch*);
static u32 w2c_watch_f336(w2c_watch*, u32);
static void w2c_watch_f337(w2c_watch*, u32, u64, u64, u32);
static void w2c_watch_f338(w2c_watch*, u32, u64, u64, u32);
static f64 w2c_watch_f339(w2c_watch*, u64, u64);
static void w2c_watch_f340(w2c_watch*, u32);
static u32 w2c_watch_f341(w2c_watch*);
static u32 w2c_watch_stackSave_0(w2c_watch*);
static void w2c_watch_stackRestore_0(w2c_watch*, u32);
static u32 w2c_watch_stackAlloc_0(w2c_watch*, u32);
static u32 w2c_watch_emscripten_stack_get_current_0(w2c_watch*);
static void w2c_watch_emscripten_stack_init_0(w2c_watch*);
static void w2c_watch_emscripten_stack_set_limits_0(w2c_watch*, u32, u32);
static u32 w2c_watch_emscripten_stack_get_free_0(w2c_watch*);
static u32 w2c_watch_emscripten_stack_get_base_0(w2c_watch*);
static u32 w2c_watch_emscripten_stack_get_end_0(w2c_watch*);
static u32 w2c_watch_fflush_0(w2c_watch*, u32);
static u32 w2c_watch_dynCall_idi_0(w2c_watch*, u32, f64, u32);
static void w2c_watch_dynCall_vi_0(w2c_watch*, u32, u32);
static u32 w2c_watch_dynCall_iiii_0(w2c_watch*, u32, u32, u32, u32);
static u32 w2c_watch_dynCall_iii_0(w2c_watch*, u32, u32, u32);
static void w2c_watch_dynCall_v_0(w2c_watch*, u32);
static void w2c_watch_dynCall_viii_0(w2c_watch*, u32, u32, u32, u32);
static void w2c_watch_dynCall_vii_0(w2c_watch*, u32, u32, u32);
static u32 w2c_watch_dynCall_iiiiii_0(w2c_watch*, u32, u32, u32, u32, u32, u32);
static u32 w2c_watch_dynCall_ii_0(w2c_watch*, u32, u32);
static u64 w2c_watch_f361(w2c_watch*, u32, u32, u64, u32);
static u32 w2c_watch_dynCall_iidiiii_0(w2c_watch*, u32, u32, f64, u32, u32, u32, u32);
static u32 w2c_watch_dynCall_jiji_0(w2c_watch*, u32, u32, u32, u32, u32);
static void w2c_watch_asyncify_start_unwind_0(w2c_watch*, u32);
static void w2c_watch_asyncify_stop_unwind_0(w2c_watch*);
static void w2c_watch_asyncify_start_rewind_0(w2c_watch*, u32);
static void w2c_watch_asyncify_stop_rewind_0(w2c_watch*);
static u32 w2c_watch_asyncify_get_state_0(w2c_watch*);

#ifdef __cplusplus
}
#endif

#endif  /* WATCH_H_GENERATED_ */


